default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: testApp_development

test:
  <<: *default
  database: testApp_test

production:
  <<: *default
  database: testApp_production
  username: 
  password: 